# Generated by Django 4.2 on 2023-04-30 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_employee_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='employee',
            field=models.CharField(default='Employee', max_length=50),
        ),
    ]
