# Generated by Django 4.2 on 2023-05-02 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_employee_employee'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='salary',
            new_name='salary_per_day',
        ),
    ]
