# Generated by Django 4.2 on 2023-06-16 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_rename_salary_employee_salary_per_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='entry_time',
            field=models.TimeField(default='09:00:00'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='leave_time',
            field=models.TimeField(default='17:00:00'),
        ),
    ]
